function plot_traces(trial_data,params)
% function to plot signal traces and their average
    % parameter setup
    signals = [];
    linestyle = '-';
    color = [0 0 0];
    trials_to_plot = 1:length(trial_data);
    trials_to_use = 1:length(trial_data);
    plot_dim = 3;
    saturation = 1;
    alpha = 1;
    start_dot = false;
    dot_size = 250;
    assignParams(who,params)
    
    % sanity check
    signals = check_signals(trial_data(1),signals);
    
    % subselect trials
    td = trial_data(trials_to_use);
    td_select = trial_data(trials_to_plot);
    
    % get actual color
    new_color = hsv2rgb([1 saturation 1] .* rgb2hsv(color));
    
    % plot individual traces
    hold_stat = ishold;
    for trialnum = 1:length(td_select)
        data = get_vars(td_select(trialnum),signals);
        if plot_dim==2
            p = plot(...
                data(:,1),...
                data(:,2),...
                linestyle,...
                'linewidth',0.25,...
                'color',new_color);
            if alpha ~= 1
                p.Color(4) = alpha;
            end
        elseif plot_dim==3
            p = plot3(...
                data(:,1),...
                data(:,2),...
                data(:,3),...
                linestyle,...
                'linewidth',0.25,...
                'color',new_color);
            if alpha ~= 1
                p.Color(4) = alpha;
            end
        end
        hold on
    end
    
    % plot average trace
    td_avg = trialAverage(td,'all');
    data = get_vars(td_avg,signals);
    if plot_dim==2
        p = plot(...
            data(:,1),...
            data(:,2),...
            linestyle,...
            'linewidth',2,...
            'color',new_color);
        if start_dot
            scatter(...
                data(1,1),...
                data(1,2),...
                dot_size,...
                new_color,...
                'filled')
        end
    elseif plot_dim==3
        p = plot3(...
            data(:,1),...
            data(:,2),...
            data(:,3),...
            linestyle,...
            'linewidth',2,...
            'color',new_color);
        if start_dot
            scatter3(...
                data(1,1),...
                data(1,2),...
                data(1,3),...
                dot_size,...
                new_color,...
                'filled')
        end
    end
    
    if ~hold_stat
        hold off
    end
end